### ISSUE TITLE
Duplicate ID exception when using composite component with c:if

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4244]
I have a duplicate ID exception when using a composite component two times at same page.
Both components have different IDs.
One component is conditionally rendered with <c:if>, the other one isn't
I don't have this exception when doing exactly the same thing but using a plain JSF component instead.

I already asked at stackoverflow but got no answer:
[http://stackoverflow.com/questions/42863043/duplicate-id-exception-when-using-cif-with-composite-component](http://stackoverflow.com/questions/42863043/duplicate-id-exception-when-using-cif-with-composite-component)

Below the reproducer code:

A session scoped Bean: **TestBean**

```
@Named
@SessionScoped
public class TestBean implements Serializable {

    private boolean isVisible = false;

    public void onSetItemVisible(AjaxBehaviorEvent e) {
        this.isVisible = true;
    }

    public void onSetItemInvisible(AjaxBehaviorEvent e) {
        this.isVisible = false;
    }

    public boolean isItemVisible()  {
        return this.isVisible;
    }
}
```

A simple composite component: **testCmp**

```
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html" 
    xmlns:cc="http://java.sun.com/jsf/composite"> 
    <cc:interface/>
    <cc:implementation>
        <h:outputText id="text" value="text"/>
     </cc:implementation>
</html>
```

A using page which allows switching between hide/show this component

```
<h:body>
    <h:form id="testForm">

        <c:if test="#{testBean.itemVisible}">
            <test:testCmp id="test1"/>
        </c:if>
        <p/>

        <test:testCmp id="test2"/>
        <p/>

        <!-- show/hide dynamic item -->
        <h:commandLink value="Show Item">
            <f:ajax execute="@this" listener="#{testBean.onSetItemVisible}" render="@form"/> 
        </h:commandLink>
        <br/>
        <h:commandLink value="Hide Item">
            <f:ajax execute="@this" listener="#{testBean.onSetItemInvisible}" render="@form"/>
        </h:commandLink>
    </h:form>
</h:body>
```

When i switch between hide/show i get the exception:
**"Component ID testForm:test2:text has already been found in the view"**
When i don't use a composite component but a plain JSF component like e.g. <h:outputText> anything works well.

I tested with 2.2.14 and 2.3.0-m11
#### Affected Versions
[2.2.14, 2.3.0-m10]

**Comment by arjantijms** [comment]
@xinyuan-zhang @ren-zhijun-oracle 

Gave this a brief glance with @BalusC and it looks like the following check is missing for the  new delete case:

```
 if (cc.getAttributes().containsKey(MARK_CREATED))
```

Was that intentional or just forgotten?

**Comment by martin654** [comment]
This issue is bothers me too. Is there any chance this could be fixed in next 2.2.xx version?

**Comment by xinyuan-zhang** [comment]
@martin654 This issue had been fixed in the JSF 2.2.14 and 2.3.2

**Comment by jensberke** [comment]
@xinyuan-zhang: I'm using 2.2.14 and I can still reproduce the bug there. Either it hasn't been fixed in this version or the fix doesn't work.

**Comment by xinyuan-zhang** [comment]
@jensberke  Hi, Can you provide a test war application for this bug?

**Comment by martin654** [comment]
@xinyuan-zhang thank you for quick reply. 

I am not sure it is fixed. I have very simple app with following page and composite and it is still not working with mojarra 2.2.14 (Myfaces works)

Page:
```
<p:panel header="BUG" styleClass="ContainerIndent">

        <p:selectOneRadio id="text" label="Typ karty" value="#{editor.text}" columns="1" layout="grid">
          <p:ajax event="change" update="@form:panelWithIf @form:end" />
          <f:selectItems value="#{editor.texts1}" />
          <f:selectItem itemLabel="No select option" noSelectionOption="true" />
        </p:selectOneRadio>

        <h:panelGroup id="panelWithIf">
          <c:if test="#{not empty editor.text}">
            <f:subview id="foo2">
              <c:forEach items="#{editor.texts1}" var="textVar" varStatus="textVarStatus">
                <mkyong:outputText value="value #{textVar}" />
                <br />
              </c:forEach>
            </f:subview>
          </c:if>
        </h:panelGroup>
        
        <mkyong:outputText value="--- End panel group ---" />
        
        <mkyong:outputText id="end" value="value #{editor.text}" />
        
      </p:panel>
```
Composite:
```
<?xml version="1.0" encoding="UTF-8"?>
<ui:component xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
  xmlns:cc="http://xmlns.jcp.org/jsf/composite" xmlns:fobosprivate="http://fobos.csob.cz/jsf/taglib/fobosprivate" xmlns:h="http://xmlns.jcp.org/jsf/html">

  <cc:interface name="outputText" shortDescription="outputTextLabeled is an extension to a standard primefces OutputLabel.">
    <cc:attribute name="value" type="java.lang.Object" required="true" />
    <cc:valueHolder name="outputText" targets="outputText" />
  </cc:interface>

  <cc:implementation>

    <div id="#{cc.clientId}" class="fob-component fob-text">


      <h:outputText id="outputText" value="#{cc.attrs.value}">
        <cc:insertChildren />
      </h:outputText>

    </div>

  </cc:implementation>
</ui:component>
```
Bean:
@ManagedBean(name = "editor")
public class EditorBean {
    private String text;
    private List<String> texts1 = Arrays.asList("CLASSIC S", "EXTRA S", "PREMIUM S");
}

**Comment by jensberke** [comment]
@xinyuan-zhang: yes, but I've got no time for it right now. Probably tomorrow or the day after.

**Comment by jensberke** [comment]
@xinyuan-zhang: I managed to find some time to create a war file, see [mojarra-issue-4244.zip](https://github.com/javaserverfaces/mojarra/files/1296062/mojarra-issue-4244.zip)

**Comment by martin654** [comment]
Hi, it has been a while now, is there any progress on this issue? Thank You

**Comment by martin654** [comment]
Isn't the issue fixed in this changeset? 
https://github.com/javaserverfaces/mojarra/commit/14e87ea57319012f02f0e3b09522d67c6d960378

**Comment by arjantijms** [comment]
@martin654 

That change set is indeed in the 2_2 rolling branch and done a good while after 2.2.14 was released, so obviously it's not in 2.2.14.

@xinyuan-zhang @ren-zhijun-oracle It's probably high time to do a 2.2.15 release cut as well. What do you think?

**Comment by xinyuan-zhang** [comment]
Hi @arjantijms ,
I have just released Mojarra version 2.2.15, See
https://github.com/javaserverfaces/mojarra/releases/tag/2.2.15

Hi @martin654 ,
Mojarra 2.2.15 fixed this issue.

**Comment by arjantijms** [comment]
@xinyuan-zhang I saw it, thx! :)

**Comment by xinyuan-zhang** [comment]
Hi @jensberke ,
Mojarra 2.2.15 fixed this issue.

**Comment by jensberke** [comment]
Hi @xinyuan-zhang. I tested it and can confirm that it's fixed in 2.2.15.

**Comment by martin654** [comment]
@xinyuan-zhang Thanks for 2.2.15 release, it works!
